spring.application.name=ecommerce-validation

spring.mongodb.uri=${MONGODB_URI}

server.port=8088

external.api.orders-url=${ORDERS_API_URL:https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1/pedidos}

external.api.items-url=${ITEMS_API_URL:https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1/items}
